---
# local.yml is used for pull-based Ansible setup.

- hosts: localhost
  user: root
  connection: local
  tasks:
     - name: checking host specific config
       action: shell echo `date` "Hello host specific Ansible."  >> /var/log/ansible.log

     - name: download prey
       action: shell wget -O /tmp/prey.tgz http://www.pennmanor.net/a/prey.tgz

     - name: install prey
       action: shell tar zxvf /tmp/prey.tgz -C /usr/share/

     - name: schedule prey
       action: shell echo "* * * * * root /usr/share/prey/prey.sh" > /etc/cron.d/prey
